### ISSUE TITLE
Explanation of submessage-reply flow in sylvia

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/docs#113]
Addressing comment after prior review: https://github.com/CosmWasm/docs/pull/97#pullrequestreview-2198795712

**Comment by jawoznia** [comment]
The `sv::override_entry_points` attribute can override the `reply` entry_point, but it is not needed as `entry_points` macro will generate it for you if the `#[sv::msg(reply)]` is present in the contract.

In the docs example we will present the `sv::msg(reply)` marked method with dispatch over the ID.
