### ISSUE TITLE
Rewrite `Deque`

### ISSUE THREAD

**Issue by uint** [CosmWasm/docs#52]
Move toward more use-case-driven docs, probably!

**Comment by uint** [comment]
Hi @0xFable! Most of Confio devs are currently working on this new docs portal, and we're using these tickets to organize our work. We were going to tackle this one soon. Are you trying to submit your proposal here?

**Comment by 0xFable** [comment]
Hi @uint 
Thanks for the ping, I had hoped to have gotten to it sooner. 
Opened a PR and linked it to this issue. Up for helping with other ones pls make issues for anything that Confio devs aren't gonna immediately handle and ill try cover a few of them.
Happy to help anyway I can

**Comment by 0xFable** [comment]
Hey all, I see one piece of feedback left on vercel but I cannot see what it is, could you add me to the team on vercel or add the comment elsewhere ?

**Comment by uint** [comment]
> Hey all, I see one piece of feedback left on vercel but I cannot see what it is, could you add me to the team on vercel or add the comment elsewhere ?

The feedback is from @hashedone that the links don't render right. Otherwise, the thing looks good!

![image](https://github.com/user-attachments/assets/3987850d-3941-4c24-bb42-2b479e15639c)

[Did you manage to get a live preview of the docs with `npm run dev`?](https://github.com/CosmWasm/docs?tab=readme-ov-file#how-can-i-contribute) You can run it locally!
