### ISSUE TITLE
Possibility to highlight relevant code parts

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/docs#98]
Can we add a possibility in the code examples to highlight relevant lines? The best would probably be to dim most of the code and only make normal coloring for the relevant parts for the reader to focus on them, but any solution that moves attention to only relevant lines of the holistic example would most likely work. @abefernan ideas?

**Comment by abefernan** [comment]
You can highlight individual lines or ranges like this (first line):

```
```rust {2, 5-7, 9}
#[cfg_attr(not(feature = "library"), sylvia::entry_points)]
#[contract]
impl CounterContract {
    pub const fn new() -> Self {
        Self {
            count: Item::new("count"),
        }
    }
···
```

Will render this:

![image](https://github.com/user-attachments/assets/116948fe-3441-4be0-a501-2e003a40ce50)
